E_i: !!float 1e9 
E_f: !!float 1e6
    
deflection: [
    'bremstsaiapproximation', 
    'ioniznaive',
    'photoborogpetrukhin',
    'epairginneken'] ### same as default
    
e_cut: 500
v_cut: 1
cont_rand: False
scattering_method: "moliere"
deflection_type: "stochastic"
    
table_path: "/Users/pgutjahr/.cache/PROPOSAL" # mac mini
# table_path: "/net/nfshome/home/pgutjahr/.cache/PROPOSAL" # vollmond

file_name: "total_defl"
output_folder:  "icrc2023/data/total_defl_moliere_1PeV_1TeV_ecut500"
    
n_CPU:  8
n_jobs:  40
n_events_per_job: 2500
### total_events = n_jobs * n_events_per_job
rnd_state_seed: 5