continuous_energies: True
# if continuous_energies is True: E_f sets min and max values
E_i: !!float 1e9
E_f: [!!float 1e9, !!float 1e3]
    
deflection: [
    'bremstsaiapproximation', 
    'ioniznaive',
    'photoborogpetrukhin',
    'epairginneken'] ### same as default
    
e_cut: 500
v_cut: 1
cont_rand: False
scattering_method: "moliere"
deflection_type: "m_scat+stochastic"
    
table_path: "/Users/pgutjahr/.cache/PROPOSAL" # mac mini
# table_path: "/net/nfshome/home/pgutjahr/.cache/PROPOSAL" # vollmond

file_name: "total_defl_continuous_E_f"
output_folder:  "icrc2023/data/total_defl_moliere_1PeV_continuous_E_f"
    
n_CPU:  8
n_jobs:  8
n_events_per_job: 10000
### total_events = n_jobs * n_events_per_job
rnd_state_seed: 3