E_i: !!float 1e9 # 1 PeV 
E_f: !!float 1e5 # 100 GeV
    
deflection: [
    'bremsginneken', 
    'ioniznaive',
    'photoginneken',
    'epairginneken'] ### same as default
    
e_cut: !!float 1e10
v_cut: 0.05
cont_rand: False
scattering_method: "moliere"
deflection_type: "m_scat+stochastic"
    
# table_path: "/Users/pgutjahr/.cache/PROPOSAL" # mac mini
# table_path: "/Users/pascalgutjahr/.cache/PROPOSAL" # lehrstuhl macbook
table_path: "/net/nfshome/home/pgutjahr/.cache/PROPOSAL" # vollmond

file_name: "total_defl"
output_folder:  "data/e_cut_v_cut_check"
    
n_CPU:  25
n_jobs:  25
n_events_per_job: 2000 
### total_events = n_jobs * n_events_per_job
rnd_state_seed: 3

interpol_nodes: 200