E_i: 199  
E_f: !!float 1e1 
    
deflection: [
    'bremsginneken', 
    'ioniznaive',
    'photoginneken',
    'epairginneken']
medium: "hydrogen"
interpol_nodes: 200
    
e_cut: !!float 1e10
v_cut: !!float 1e-5
cont_rand: False
scattering_method: "moliere"
deflection_type: "m_scat+stochastic"
    
# table_path: "/Users/pgutjahr/.cache/PROPOSAL" # mac mini
# table_path: "/Users/pascalgutjahr/.cache/PROPOSAL" # lehrstuhl macbook
table_path: "/net/nfshome/home/pgutjahr/.cache/PROPOSAL" # vollmond

file_name: "attwood"
output_folder:  "data/attwood_199MeV_hydrogen"
    
n_CPU: 40
n_jobs: 100
n_events_per_job: 100000  
### total_events = n_jobs * n_events_per_job
rnd_state_seed: 3
max_dist: 10.9