E_i: !!float 1e9 # 1 PeV 
E_f: !!float 1e5 # 100 GeV
    
deflection: [
    'tsaiapproximationbremsstrahlung', 
    'naivionization',
    'borogpetrukhinnuclearinteraction',
    'kelnerpairproduction'] ### same as default
    
e_cut: 500
v_cut: 0.05
cont_rand: True
scattering_method: "highlandintegral"
deflection_type: "m_scat+stochastic"
    
# table_path: "/Users/pgutjahr/.cache/PROPOSAL" # mac mini
# table_path: "/Users/pascalgutjahr/.cache/PROPOSAL" # lehrstuhl macbook
table_path: "/net/nfshome/home/pgutjahr/.cache/PROPOSAL" # vollmond

file_name: "total_defl"
output_folder:  "data/cont_rand_check"
    
n_CPU:  25
n_jobs:  50
n_events_per_job: 1000 
### total_events = n_jobs * n_events_per_job
rnd_state_seed: 3