# Macro file for example B1
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfThreads 4
#
# Initialize kernel
/run/initialize
#
/control/verbose 2
# /run/verbose 2
/run/printProgress 1000
/event/verbose 0
# /tracking/verbose 1
# 
/gun/particle mu-
/gun/energy 168.9 MeV # 199 MeV
# /tracking/verbose 2
#
/run/beamOn 200000
