E_i: !!float 1e6 
E_f: !!float 1e5 
    
deflection: [
    'tsaiapproximationbremsstrahlung', 
    'naivionization',
    'borogpetrukhinnuclearinteraction',
    'kelnerpairproduction'] ### same as default
    
e_cut: 500
v_cut: 0.05
cont_rand: False
scattering_method: "highlandintegral"
deflection_type: "m_scat+stochastic"
    
# table_path: "/Users/pgutjahr/.cache/PROPOSAL" # mac mini
table_path: "/Users/pascalgutjahr/.cache/PROPOSAL" # lehrstuhl macbook
# table_path: "/net/nfshome/home/pgutjahr/.cache/PROPOSAL" # vollmond

file_name: "data_along_test"
output_folder:  "data/data_along_test"
    
n_CPU:  2
n_jobs:  4
n_events_per_job: 10  
### total_events = n_jobs * n_events_per_job
rnd_state_seed: 3

get_data_along_track: True