E_i: !!float 1e9 
E_f: !!float 1e6 
    
deflection: [
    'bremsginneken', 
    'ioniznaive',
    'photoginneken',
    'epairginneken'] ### same as default
    
e_cut: 500
v_cut: 0.05
cont_rand: False
scattering_method: "highlandintegral"
deflection_type: "m_scat+stochastic"
    
# table_path: "/Users/pgutjahr/.cache/PROPOSAL" # mac mini
# table_path: "/Users/pascalgutjahr/.cache/PROPOSAL" # lehrstuhl macbook
table_path: "/net/nfshome/home/pgutjahr/.cache/PROPOSAL" # vollmond

file_name: "test"
output_folder:  "data"
    
n_CPU:  1
n_jobs:  1
n_events_per_job: 10 
### total_events = n_jobs * n_events_per_job
rnd_state_seed: 3

interpol_nodes: 200