E_i: !!float 1e6 # in MeV
E_f: !!float 1e3 # in MeV
n_events: 10000
max_dist: !!float 1e9

v_cut: 0.05
e_cut: 500 # 'np.inf'
cont_rand: True

table_path: '/Users/pgutjahr/.cache/PROPOSAL' # macbook pro
# table_path: '/net/nfshome/home/pgutjahr/.cache/PROPOSAL' # vollmond
remove_old_tables: False

deflections: {
  'bremsginneken', # 'bremstsaiapproximation', 
  'ioniznaive',
  'photoginneken', # 'photoborogpetrukhin',
  'epairginneken'
}
scattering_method: 'highland'

rnd_seed: 2

hdf_file: 'ginneken'


