E_i: !!float 3e8 # 3e5 logging # 1e6 error
E_f: !!float 3e2 # 1e1 # propagate to muon mass
    
deflection: [
    'bremsginneken', 
    'ioniznaive',
    'photoginneken',
    'epairginneken'] 
    
e_cut: 500
v_cut: 0.05
cont_rand: False
scattering_method: "moliere"
deflection_type: "m_scat+stochastic"
    
# table_path: "/Users/pgutjahr/.cache/PROPOSAL" # mac mini
table_path: "/Users/pascalgutjahr/.cache/PROPOSAL" # lehrstuhl macbook
# table_path: "/net/nfshome/home/pgutjahr/.cache/PROPOSAL" # vollmond

file_name: "MUSIC"
output_folder:  "data/compare_MUSIC"
    
n_CPU: 1 # 30
n_jobs: 1 # 100
n_events_per_job: 3305 # 10000
### total_events = n_jobs * n_events_per_job
rnd_state_seed: 16

max_dist: !!float 3e5 # 3 km
medium: "water"

interpol_nodes: 200
